//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projects_Web_Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status_Table
    {
        public System.DateTime OrderPlacedDate { get; set; }
        public int OrderID { get; set; }
        public int ProductID { get; set; }
        public string Type { get; set; }
        public string ProductName { get; set; }
        public int Quantity { get; set; }
        public decimal TotalCost { get; set; }
        public string Status { get; set; }
    }
}
